# Generated by Django 3.0.7 on 2020-07-03 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('plot', models.CharField(max_length=400)),
                ('image', models.CharField(max_length=120)),
                ('recentdate', models.DateField(auto_now=True)),
                ('episodes', models.IntegerField()),
                ('year', models.IntegerField()),
                ('webid', models.CharField(max_length=20)),
                ('season', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reqtype', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('plot', models.CharField(max_length=400)),
                ('image', models.CharField(max_length=120)),
                ('reqdate', models.DateField(auto_now_add=True)),
                ('votes', models.IntegerField()),
                ('requser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
