# Generated by Django 3.0.7 on 2020-07-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='image',
            field=models.ImageField(upload_to='posters/'),
        ),
    ]
