# Generated by Django 3.0.7 on 2020-07-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20200703_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='path',
            field=models.CharField(default='temp/path', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='show',
            name='category',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='show',
            name='image',
            field=models.ImageField(blank=True, upload_to='posters/'),
        ),
        migrations.AlterField(
            model_name='show',
            name='plot',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='show',
            name='season',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='webid',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='show',
            name='year',
            field=models.IntegerField(blank=True),
        ),
    ]
