# Generated by Django 3.0.8 on 2020-07-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_auto_20200704_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='season',
        ),
        migrations.AddField(
            model_name='show',
            name='airing',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
