# Generated by Django 3.0.8 on 2020-07-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_auto_20200710_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='airing',
            field=models.BooleanField(blank=True),
        ),
    ]
