# Generated by Django 3.0.8 on 2020-07-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_auto_20200713_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='reqtype',
        ),
        migrations.AlterField(
            model_name='requests',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reqposters/'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
