# Generated by Django 3.0.8 on 2020-07-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0009_auto_20200716_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='votes',
        ),
        migrations.AddField(
            model_name='requests',
            name='webid',
            field=models.CharField(default='fakeid', max_length=60),
            preserve_default=False,
        ),
    ]
