# Generated by Django 3.0.8 on 2020-07-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0011_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='isfilled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requests',
            name='isrejected',
            field=models.BooleanField(default=False),
        ),
    ]
