# Generated by Django 3.0.8 on 2020-07-20 09:15

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0013_remove_votes_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\posters\\'), upload_to='reqposters/'),
        ),
        migrations.AlterField(
            model_name='show',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\posters\\'), upload_to='posters/'),
        ),
    ]
