# Generated by Django 3.0.8 on 2020-07-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0014_auto_20200720_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='max_episode',
            field=models.SmallIntegerField(null=True),
        ),
    ]
