# Generated by Django 3.0.8 on 2020-07-22 07:52

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0016_auto_20200722_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/posters/', location='C:\\ServerRelated\\posters\\'), upload_to='reqposters/'),
        ),
        migrations.AlterField(
            model_name='show',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/posters/', location='C:\\ServerRelated\\posters\\'), upload_to='posters/'),
        ),
    ]
