# Generated by Django 3.0.8 on 2020-07-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylogin', '0003_auto_20200720_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
