# Generated by Django 3.0.8 on 2020-07-20 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mylogin', '0005_auto_20200720_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='invites',
            name='email',
            field=models.CharField(default='lmao', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ForgetPassword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key1', models.CharField(max_length=10)),
                ('key2', models.CharField(max_length=6)),
                ('requser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
