# Generated by Django 3.0.8 on 2020-07-20 13:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mylogin', '0006_auto_20200720_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgetpassword',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
